// ------------------------------------------------------------------------------
//  <auto-generated>
//      Dieser Code wurde vom Coded UI-Test-Generator generiert.
//      Version: 15.0.0.0
//
//      In dieser Datei sind spezialisierte Klassen definiert, die in einem
//      Coded UI-Test verwendet werden.
//      In dieser Datei können die erforderlichen Anpassungen vorgenommen werden.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Snowwhite.Test
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = Microsoft.VisualStudio.TestTools.UITest.Input.MouseButtons;
    
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// CheckStartUpText - Verwenden Sie "CheckStartUpTextExpectedValues", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void CheckStartUpText()
        {
            #region Variable Declarations
            XamlText uIMirrormirroronthewalText = this.UISnowwhiteWindow.UIMirrormirroronthewalText;
            #endregion

            // Sicherstellen, dass die Eigenschaft 'Name' von "Mirror mirror on the wall..." Bezeichnung ist gleich 'Mirror mirror on the wall...'
            Assert.AreEqual(this.CheckStartUpTextExpectedValues.UIMirrormirroronthewalTextName, uIMirrormirroronthewalText.Name, "Startup Text not found!");
        }
        
        #region Properties
        public virtual CheckStartUpTextExpectedValues CheckStartUpTextExpectedValues
        {
            get
            {
                if ((this.mCheckStartUpTextExpectedValues == null))
                {
                    this.mCheckStartUpTextExpectedValues = new CheckStartUpTextExpectedValues();
                }
                return this.mCheckStartUpTextExpectedValues;
            }
        }
        
        public UISnowwhiteWindow UISnowwhiteWindow
        {
            get
            {
                if ((this.mUISnowwhiteWindow == null))
                {
                    this.mUISnowwhiteWindow = new UISnowwhiteWindow();
                }
                return this.mUISnowwhiteWindow;
            }
        }
        #endregion
        
        #region Fields
        private CheckStartUpTextExpectedValues mCheckStartUpTextExpectedValues;
        
        private UISnowwhiteWindow mUISnowwhiteWindow;
        #endregion
    }
    
    /// <summary>
    /// An "CheckStartUpText" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class CheckStartUpTextExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Sicherstellen, dass die Eigenschaft 'Name' von "Mirror mirror on the wall..." Bezeichnung ist gleich 'Mirror mirror on the wall...'
        /// </summary>
        public string UIMirrormirroronthewalTextName = "Mirror mirror on the wall...";
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "15.0.26208.0")]
    public class UISnowwhiteWindow : XamlWindow
    {
        
        public UISnowwhiteWindow()
        {
            #region Suchkriterien
            this.SearchProperties[XamlControl.PropertyNames.Name] = "Snowwhite";
            this.SearchProperties[XamlControl.PropertyNames.ClassName] = "Windows.UI.Core.CoreWindow";
            this.WindowTitles.Add("Snowwhite");
            #endregion
        }
        
        #region Properties
        public XamlText UIMirrormirroronthewalText
        {
            get
            {
                if ((this.mUIMirrormirroronthewalText == null))
                {
                    this.mUIMirrormirroronthewalText = new XamlText(this);
                    #region Suchkriterien
                    this.mUIMirrormirroronthewalText.SearchProperties[XamlText.PropertyNames.Name] = "Mirror mirror on the wall...";
                    this.mUIMirrormirroronthewalText.WindowTitles.Add("Snowwhite");
                    #endregion
                }
                return this.mUIMirrormirroronthewalText;
            }
        }
        #endregion
        
        #region Fields
        private XamlText mUIMirrormirroronthewalText;
        #endregion
    }
}
